from sqlalchemy import Column, Integer, String, Text, Date, ForeignKey, JSON, Float
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship

Base = declarative_base()


class Theme(Base):
    """Korean market themes (e.g., AI Semiconductor, EV Battery)"""
    __tablename__ = "themes"
    
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(100), unique=True, nullable=False)
    keywords = Column(Text, nullable=True)  # JSON list of related English keywords
    
    # Relationships
    stocks_kr = relationship("StockKR", back_populates="theme")
    recommended_themes = relationship("RecommendedTheme", back_populates="theme")


class StockUS(Base):
    """US Stock information"""
    __tablename__ = "stocks_us"
    
    ticker = Column(String(10), primary_key=True)
    name = Column(String(200), nullable=False)
    sector = Column(String(100), nullable=True)
    theme_id = Column(Integer, ForeignKey("themes.id"), nullable=True)


class StockKR(Base):
    """Korean Stock information"""
    __tablename__ = "stocks_kr"
    
    ticker = Column(String(10), primary_key=True)  # e.g., "005930" for Samsung
    name = Column(String(200), nullable=False)
    sector = Column(String(100), nullable=True)
    theme_id = Column(Integer, ForeignKey("themes.id"), nullable=True)
    
    # Relationships
    theme = relationship("Theme", back_populates="stocks_kr")


class DailyBriefing(Base):
    """Daily US market summary generated by AI"""
    __tablename__ = "daily_briefings"
    
    date = Column(Date, primary_key=True)
    us_summary = Column(Text, nullable=False)  # AI generated summary
    market_sentiment = Column(String(50), nullable=True)  # Fear/Greed
    key_indices_json = Column(JSON, nullable=True)  # Dow, Nasdaq, S&P changes


class RecommendedTheme(Base):
    """The core result: recommended Korean themes based on US market"""
    __tablename__ = "recommended_themes"
    
    id = Column(Integer, primary_key=True, index=True)
    date = Column(Date, nullable=False, index=True)
    theme_id = Column(Integer, ForeignKey("themes.id"), nullable=False)
    reason = Column(Text, nullable=False)  # Why this theme is hot today
    related_us_stock = Column(String(10), nullable=True)  # The cause ticker
    impact_score = Column(Integer, nullable=False)  # 1-10
    
    # Relationships
    theme = relationship("Theme", back_populates="recommended_themes")
