from sqlalchemy import (
    Column,
    Integer,
    String,
    Text,
    Date,
    ForeignKey,
    JSON,
    Boolean,
    DateTime,
)
from sqlalchemy.sql import func
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship

Base = declarative_base()


class Theme(Base):
    """Korean market themes (e.g., AI Semiconductor, EV Battery)"""

    __tablename__ = "themes"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(100), unique=True, nullable=False)
    keywords = Column(Text, nullable=True)  # JSON list of related English keywords

    # Relationships
    stocks_kr = relationship("StockKR", back_populates="theme")
    recommended_themes = relationship("RecommendedTheme", back_populates="theme")


class StockUS(Base):
    """US Stock information"""

    __tablename__ = "stocks_us"

    ticker = Column(String(10), primary_key=True)
    name = Column(String(200), nullable=False)
    sector = Column(String(100), nullable=True)
    theme_id = Column(Integer, ForeignKey("themes.id"), nullable=True)


class StockKR(Base):
    """Korean Stock information"""

    __tablename__ = "stocks_kr"

    ticker = Column(String(10), primary_key=True)  # e.g., "005930" for Samsung
    name = Column(String(200), nullable=False)
    sector = Column(String(100), nullable=True)
    theme_id = Column(Integer, ForeignKey("themes.id"), nullable=True)

    # Relationships
    theme = relationship("Theme", back_populates="stocks_kr")


class DailyBriefing(Base):
    """Daily US market summary generated by AI"""

    __tablename__ = "daily_briefings"

    id = Column(Integer, primary_key=True, index=True)
    date = Column(Date, unique=True, nullable=False)
    content = Column(Text, nullable=True)  # Legacy: full text summary

    # Structured fields for frontend consumption
    us_summary = Column(Text, nullable=True)
    market_sentiment = Column(
        String(50), nullable=True
    )  # e.g. "Greed", "Fear", "Neutral"
    key_indices_json = Column(
        JSON, nullable=True
    )  # {"S&P 500": {"value": 5200, "change_percent": 1.2}, ...}
    fear_greed_score = Column(Integer, nullable=True)  # 0-100

    # Store JSON structure as well for structured UI
    structured_content = Column(JSON, nullable=True)

    created_at = Column(DateTime(timezone=True), server_default=func.now())


class MarketDataCache(Base):
    """Cache for external API responses to prevent rate limits"""

    __tablename__ = "market_data_cache"

    key = Column(String(50), primary_key=True)  # e.g. "US_INDICES", "US_TOP_GAINERS"
    data = Column(JSON, nullable=False)
    updated_at = Column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )


class RecommendedTheme(Base):
    """The core result: recommended Korean themes based on US market"""

    __tablename__ = "recommended_themes"

    id = Column(Integer, primary_key=True, index=True)
    date = Column(Date, nullable=False, index=True)
    theme_id = Column(Integer, ForeignKey("themes.id"), nullable=False)
    reason = Column(Text, nullable=False)  # Why this theme is hot today
    related_us_stock = Column(String(10), nullable=True)  # The cause ticker
    impact_score = Column(Integer, nullable=False)  # 1-10

    # Relationships
    theme = relationship("Theme", back_populates="recommended_themes")


class User(Base):
    """User account for personalization"""

    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    user_uuid = Column(
        String(36), unique=True, nullable=False, index=True
    )  # UUID string
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    watchlists = relationship("Watchlist", back_populates="user")


class Watchlist(Base):
    """User's interested stocks (KR)"""

    __tablename__ = "watchlists"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    stock_kr_ticker = Column(String(10), ForeignKey("stocks_kr.ticker"), nullable=False)
    alert_enabled = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    user = relationship("User", back_populates="watchlists")
    stock = relationship("StockKR")


class ValueChain(Base):
    """Deep connection between US Driver Stock and KR Beneficiary"""

    __tablename__ = "value_chains"

    id = Column(Integer, primary_key=True, index=True)
    theme_id = Column(Integer, ForeignKey("themes.id"), nullable=False)
    parent_stock_us = Column(
        String(10), ForeignKey("stocks_us.ticker"), nullable=False
    )  # The Cause (e.g., NVDA)
    child_stock_kr = Column(
        String(10), ForeignKey("stocks_kr.ticker"), nullable=False
    )  # The Effect (e.g., 000660)
    relation_type = Column(
        String(50), nullable=False
    )  # e.g., "Supplier", "Competitor", "Sympathy"
    description = Column(Text, nullable=True)  # Details (e.g., "Supplies HBM3E chips")

    # Relationships
    theme = relationship("Theme")
    us_stock = relationship("StockUS")
    kr_stock = relationship("StockKR")
